Fix build
cg-saarland/hussar pull request #1
Opened 2021-02-03 11:27 UTC by lukasmichel

- Fix building of libradar by including `atomic`. 
- Fix building of libhussar by replacing two usages of `double` with `hussar::Float`

Tested on archlinux using gcc 10.2.0 and clang 11.0.1. Tested with and without NVIDIA OptiX

2021-02-03 11:31 UTC, iRath96 requested changes

2021-02-03 11:31 UTC, iRath96 commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
@lukasmichel going single precision here is not an option. This would break as soon as our integrator takes more than 16 million samples, which isn't that uncommon of a use case actually.

2021-02-03 11:39 UTC, lukasmichel commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
That's a problem then. I can't build libhussar with `double` there when `hussar:Float` is defined as `float`: `/home/lukas/Documents/Studium/HiWi-Radar/HUSSAR/hussar/libhussar/include/hussar/integrators/path.h(469): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, hussar::Float)
`

2021-02-03 11:43 UTC, iRath96 commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
Does this problem occur when building with OptiX or without it? If it's with OptiX, can you let me know your  `__CUDA_ARCH__`?

2021-02-03 11:56 UTC, madmann91 commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
Maybe just do an explicit cast of the second argument to `double`:
```
atomicAdd(&totalWeight, (double)sampleWeight);
```
`atomicAdd` on `double` is supported since compute capability 6 (Pascal): https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicadd
For older devices, you can implement it as:
```cpp
#if __CUDA_ARCH__ < 600
__device__ double atomicAdd(double* address, double val)
{
    unsigned long long int* address_as_ull = (unsigned long long int*)address;
    unsigned long long int old = *address_as_ull, assumed;

    do {
        assumed = old;
        // Note: uses integer comparison to avoid hang in case of NaN (since NaN != NaN)
        old = atomicCAS(address_as_ull, assumed,
            __double_as_longlong(val + __longlong_as_double(assumed)));
    } while (assumed != old);

    return __longlong_as_double(old);
}
#endif
```
(this is taken from the CUDA docs)

2021-02-03 13:05 UTC, lukasmichel commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
> Does this problem occur when building with OptiX or without it? If it's with OptiX, can you let me know your `__CUDA_ARCH__`?

Only happens  with OptiX. My device is a GTX 970 with compute capability 5.2, so what @madmann91 said applies here, I think.
Compiling with `double` for `totalWeight` and `oldV` on CPU seems to work, I probably had miss-configured my CPU-build when I tried that first.

2021-02-03 13:24 UTC, iRath96 commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
@lukasmichel I suggest adding the `atomicAdd(double *, double)` polyfill for older CUDA archs (as shown by @madmann91 ) under `arch/gpu.h`.

2021-02-03 14:00 UTC, lukasmichel commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
adding it to `arch/gpu.h` is probably not the best idea, as `arch/gpu.h` already includes `integrators/path.h`. I would suggest adding it to `hussar.h`, at the same place where also the `HUSSAR_GPU` and `HUSSAR_CPU_GPU` macros are defined. I tried that last solution and it compiles fine.

2021-02-03 14:02 UTC, iRath96 commented on libhussar/include/hussar/integrators/path.h
> -    double totalWeight;
Ohh... I completely forgot about that ugly hack. In principle, `arch/gpu.h` shouldn't have to include `integrators/path.h` – but unfortunately there are still some issues with dynamic dispatch and alike that would need to be sorted out.

So yes, adding it to `hussar.h` for now is a good work around I guess.

2021-02-03 14:13 UTC, iRath96 approved these changes

2021-02-03 14:14 UTC, iRath96 commented
@lukasmichel Could you please add your OS and compiler to `README.md` as tested system?

2021-02-03 14:31 UTC, lukasmichel commented
> @lukasmichel Could you please add your OS and compiler to `README.md` as tested system?

Unortunately, there are still other problems I just discovered:
- I can't yet build the visualizer with OptiX 
- There is a problem with SDL2 (for `hussar2d`) linking on my system. I have a fix for that one which I can either add to this PR or that I can provide in a new PR

2021-02-03 14:33 UTC, iRath96 commented
> * There is a problem with SDL2 (for `hussar2d`) linking on my system. I have a fix for that one which I can either add to this PR or that I can provide in a new PR

I think it would make sense to add it to this PR, since this PR already spans different parts (libradar, libhussar) of the project.

2021-02-08 13:11 UTC, iRath96 commented
@lukasmichel I guess everything is running correctly now. Is this ready to get merged?

2021-02-08 13:14 UTC, lukasmichel commented
Yes, this should be ready to merge. 
However, maybe this should be tested on a different system than mine, especially to make sure that the changes I did to linking SDL2 are also correct for others.

2021-02-08 13:16 UTC, merged